version: '3.4'
services:
    app:
        container_name: rails
        build:
            context: ./
        volumes:
            - ./app:/app
            - ./conf/.bashrc:/root/.bashrc
            - ./conf/.vimrc:/root/.vimrc
        ports:
            - 80:3000
        environment:
            - "TZ=Asia/Tokyo"
        tty: true
        restart: always
